---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: sockshop-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: sockshop-dev
spec:
  selector:
    matchLabels:
      name: orders-db
      stage: dev
      version: "1.1"
      tier: data
      product: sockshop
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        pipeline.stage: dev
        pipeline.build: 1.1.1.0022
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        name: orders-db
        stage: dev
        version: "1.1"
        tier: data
        product: sockshop
    spec:
      containers:
      - image: mongo
        name: orders-db
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: "password"
        - name: MONGODB_USER
          value: "user"
        - name: MONGODB_PASSWORD
          value: "password"
        - name: MONGODB_DATABASE
          value: "orders-db"
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      restartPolicy: Always
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: sockshop-dev
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: sockshop-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      name: orders-db
      stage: prod
      version: "1.0"
      tier: data
      product: sockshop
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        pipeline.stage: prod-stable
        pipeline.build: 1.0.2.0114
        pipeline.project: sockshop
        support.contact: "mary.poppins@sockshop.com"
        support.channel: "#support-sockshop-data"
      labels:
        name: orders-db
        stage: prod
        version: "1.0"
        tier: data
        product: sockshop
    spec:
      containers:
      - image: mongo
        name: orders-db
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: "password"
        - name: MONGODB_USER
          value: "user"
        - name: MONGODB_PASSWORD
          value: "password"
        - name: MONGODB_DATABASE
          value: "orders-db"
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      restartPolicy: Always
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: sockshop-production
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
