apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-v1
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      app: front-end
      stage: prod
      release: stable
      version: v1
      tier: "frontend"
      product: "sockshop"
  replicas: 1
  template:
    metadata:
      annotations:
        pipeline.stage: prod-stable
        pipeline.build: 1.4.0.7424
        pipeline.project: sockshop
        support.contact: "jane.smith@sockshop.com"
        support.channel: "#support-sockshop-frontend"
        canary: v1
      labels:
        app: front-end
        stage: prod
        release: stable
        version: v1
        tier: "frontend"
        product: "sockshop"
    spec:
      containers:
      - name: front-end
        image: dynatracesockshop/front-end:0.5.0
        env:
        - name: DT_TAGS
          value: "MyFirstTag=Tag1Value MySecondTag=Tag2Value"
        - name: DT_CUSTOM_PROP
          value: "MyProp1=Prop1Value MyProd2=Prop2Value"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      nodeSelector:
        beta.kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
  namespace: sockshop-production
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: front-end
  type: ClusterIP
