---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      app: user
      stage: prod
      release: stable
      version: "1.4"
      tier: "business"
      product: "sockshop"
  replicas: 1
  template:
    metadata:
      annotations:
        pipeline.stage: prod-stable
        pipeline.build: 1.4.1.0365
        pipeline.project: sockshop
        support.contact: "tony.stark@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app: user
        stage: prod
        release: stable
        version: "1.4"
        tier: "business"
        product: "sockshop"
    spec:
      containers:
      - name: user
        image: dynatracesockshop/user:0.5.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
  namespace: sockshop-production
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: user
