---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: sockshop-production
spec:
  selector:
    matchLabels:
      name: rabbitmq
      stage: prod
      version: "1.0"
      tier: messaging
      product: sockshop
  replicas: 1
  template:
    metadata:
      annotations:
        pipeline.stage: prod-stable
        pipeline.build: 1.0.1.0005
        pipeline.project: sockshop
        support.contact: "jimmy.page@sockshop.com"
        support.channel: "#support-sockshop-middleware"
      labels:
        name: rabbitmq
        stage: prod
        version: "1.0"
        tier: messaging
        product: sockshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
      nodeSelector:
        beta.kubernetes.io/os: linux
