apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: sockshop-dev
  labels:
    app: carts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts
      stage: dev
      release: stable
      version: "2.3"
      tier: "business"
      product: "sockshop"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        pipeline.stage: dev
        pipeline.build: 2.4.0.0832
        pipeline.project: sockshop
        support.contact: "john.doe@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app: carts
        stage: dev
        release: stable
        version: "2.3"
        tier: "business"
        product: "sockshop"
    spec:
      containers:
      - name: carts
        image: wmsegar/carts:3.0
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx512m -XX:PermSize=128m -XX:MaxPermSize=128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        resources:
          limits:
            cpu: 500m
            memory: 1536Mi
          requests:
            cpu: 200m
            memory: 768Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /carts/1/items/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /carts/1/items/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 15
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux

