---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: sockshop-dev
spec:
  selector:
    matchLabels:
      app: catalogue
      stage: dev
      release: stable
      version: "3.1"
      tier: "business"
      product: "sockshop"
  replicas: 1
  template:
    metadata:
      annotations:
        pipeline.stage: dev
        pipeline.build: 3.1.1.0435
        pipeline.project: sockshop
        support.contact: "john.doe@sockshop.com"
        support.channel: "#support-sockshop-services"
      labels:
        app: catalogue
        stage: dev
        release: stable
        version: "3.1"
        tier: "business"
        product: "sockshop"
    spec:
      containers:
      - name: catalogue
        image: dynatracesockshop/catalogue:0.5.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    app: catalogue
  namespace: sockshop-dev
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: catalogue
